usuarios/applications/home/urls.py
from django.urls import path
#
from . import views

app_name = "home_app"
urlpatterns = [
    path(
        'home/', 
        views.HomePage.as_view(),
        name = 'panel'),
    path(
        'mixin/', 
        views.TemplatePrueba.as_view(),
        name = 'mixin'),
]

usuarios/applications/users/urls.py
from django.urls import path
#
from . import views

app_name = "users_app"
urlpatterns = [
    path(
        'register/', 
        views.UserRegisterView.as_view(),
        name = 'user-register'),
    path(
        'login/', 
        views.LoginUser.as_view(),
        name = 'user-login'),
    path(
        'logout/', 
        views.LogoutView.as_view(),
        name = 'user-logout'),
    path(
        'update/', 
        views.UpdatePassword.as_view(),
        name = 'user-update'),
    path(
        'user-verification/', 
        views.CodeVerificationsView.as_view(),
        name = 'user-verification'),
]

usuarios/usuarios/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
]

usuarios/applications/home/models.py
from django.db import models

# Create your models here.

usuarios/applications/home/views.py
import datetime
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse


from django.views.generic import(
    TemplateView
)
class FechaMixin(object):
    def get_context_data(self, **kwargs):
        context = super(FechaMixin, self).get_context_data(**kwargs)
        context['fecha'] = datetime.datetime.now()
        return context

class HomePage(LoginRequiredMixin, TemplateView):
    template_name = "home/index.html"
    login_url = reverse_lazy('users_app:user-login')


class TemplatePrueba(FechaMixin, TemplateView):
    template_name = "home/mixin.html"

usuarios/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Panel de Usuario</h1>
    <h3>bienvenidos:{{user.get_full_name}}</h3>
    <ul>
        <li><a href="{% url 'users_app:user-logout' %}">cerrar sesion</a></li>
        <li><a href="{% url 'users_app:user-update' %}">Actualizar Datos</a></li>
    </ul>
</body>
</html>

usuarios/templates/home/mixin.html
<h1>Probando mixin:</h1>
{{ fecha }}